### ISSUE TITLE
sqlite can't set type

### ISSUE THREAD

**Issue by smcat8** [thombashi/pytablewriter#12]
writer = pytablewriter.SqliteTableWriter()
...
writer.type_hints[0] = pytablewriter.String

but after writer.write_table(), sqlite schema will display INTEGER if first column is digit.

**Comment by thombashi** [comment]
Thank you for your report.

The problem fixed at `pytablewriter 0.45.1`.
Please try to upgrade the package and re-execute your code.

**Comment by thombashi** [comment]
I'll close the issue.
Feel free to reopen if you still have any problems about the issue.
