### ISSUE TITLE
Add TOP, BOTTOM align as option for formatting Markdown table cells

### ISSUE THREAD

**Issue by jimkohl** [thombashi/pytablewriter#13]
Hello, thank you for your work on this it saved me a bunch of time.

I'm creating a table w rows of multiple cells containing lists of items.
Each item in the list is separated by <br>.

The length of these cell lists varies across cells, 
while the largest list cell obviously consumes the most space, 
adjacent smaller cells (lists) are aligned vertically as centered, which isn't great visually.  
I would prefer being able to align to TOP.

I realize that Markdown doesn't support such a concept, 
wondering if there any ways to style a column as Align.TOP, somehow getting renderer to add 
**style="vertical-align: top;"** somehow into the html.

Considering the various flavors of markdown, I guess this wouldn't work.
Any ideas?

**Comment by thombashi** [comment]
Thank you for your feedback.

As far as I know, set vertical-align to a Markdown table could not possible with basic Markdown syntax only.
As you described, you would need to set styles via Markdown-extensions or HTML tag directory. However, that depends on Markdown processors. GFM ignore style tags.

HTML table might be a good choice to apply vertical-align to cells (GFM and most of the Markdown flavors accepts HTML tables).
`pytablewriter` has a table writer class for HTML (`HtmlTableWriter`).
I could possible to add vertical-align feature to `HtmlTableWriter` (and `Style` class) in the future.

Though, this may not what you trying to achieve to do.
What do you think about this?

**Comment by jimkohl** [comment]
That sounds like a good add to html table which I will try when you do it.  I wish the md folks would progress a bit tho!

**Comment by thombashi** [comment]
@jimkohl 
You can use `vertical_align` style with `HtmlTablewriter` of `pytablewriter 0.51.0` or later.

Example:

```py
writer = HtmlTablewriter()
writer.table_name = "vertical-align"
writer.headers = [
    "",
    "top",
    "middle",
    "bottom",
    "top-right",
    "middle-right",
    "bottom-right",
]
writer.value_matrix = [
    ["te\nst", "x", "x", "x", "x", "x", "x"],
]
writer.column_styles = [
    Style(vertical_align="baseline"),
    Style(vertical_align="top"),
    Style(vertical_align="middle"),
    Style(vertical_align="bottom"),
    Style(align="right", vertical_align="top"),
    Style(align="right", vertical_align="middle"),
    Style(align="right", vertical_align="bottom"),
]
writer.write_table()
```

Output:

```html
<table id="verticalalign">
    <caption>vertical-align</caption>
    <thead>
        <tr>
            <th></th>
            <th>top</th>
            <th>middle</th>
            <th>bottom</th>
            <th>top-right</th>
            <th>middle-right</th>
            <th>bottom-right</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td align="left">te<br>st</td>
            <td align="left" valign="top">x</td>
            <td align="left" valign="middle">x</td>
            <td align="left" valign="bottom">x</td>
            <td align="right" valign="top">x</td>
            <td align="right" valign="middle">x</td>
            <td align="right" valign="bottom">x</td>
        </tr>
    </tbody>
</table>
```

The output will be rendered by GitHub as follows:

<table id="verticalalign">
    <caption>vertical-align</caption>
    <thead>
        <tr>
            <th></th>
            <th>top</th>
            <th>middle</th>
            <th>bottom</th>
            <th>top-right</th>
            <th>middle-right</th>
            <th>bottom-right</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td align="left">te<br>st</td>
            <td align="left" valign="top">x</td>
            <td align="left" valign="middle">x</td>
            <td align="left" valign="bottom">x</td>
            <td align="right" valign="top">x</td>
            <td align="right" valign="middle">x</td>
            <td align="right" valign="bottom">x</td>
        </tr>
    </tbody>
</table>
