### ISSUE TITLE
writer.dumps() fails due to multiprocessing if __main__ is not protected 

### ISSUE THREAD

**Issue by skjerns** [thombashi/pytablewriter#27]
I'm using a script to call a table-writer method in another module.

However, due to `multiprocessing` usage, this fails, as the new processes import the unprotected script.

Can be reproduces like this:
```Python
from pytablewriter import HtmlTableWriter
# no __name__=='__main__' statement
writer = HtmlTableWriter()
writer.value_matrix  = [[1,2,3,4]]    
string = writer.dumps()
```

I'm a bit surprised that this package needs multiprocessing, are there such heavy computations to be made?

Might it be an idea to switch to `joblib.Parallel`, as in my experience it doesn't suffer from this problem? Or to disable multiprocessing/switch to multithreading (no reimport of main module necessary)?

(It's a Windows problem, as there is no `fork` on winx)

**Comment by thombashi** [comment]
You can switch to a single process by setting max_workers attribute of the writer to one:

```py
writer.max_workers = 1
```

> are there such heavy computations to be made?

Yes, the larger the data the more converting processing time will required.
However, multiprocessing is not always necessary especially for small data like your example.
It might be more desirable to `max_workers` to one as the default.
I will consider for the future release.
