### ISSUE TITLE
Example for TableWriterFactory

### ISSUE THREAD

**Issue by skjerns** [thombashi/pytablewriter#28]
I've come across the `TableWriterFactory`, and I think it might be quite useful for my project.

However, I can't seem to make it work and I could not find an example. Can you tell me how to use it?

I've tried

```Python
from pytablewriter import TableWriterFactory
writer = TableWriterFactory().create_from_file_extension('.csv')
```

But it raises an EmptyTableDataError.

I've also tried to fill the `value_matrix` etc but it didn't help.

**Comment by thombashi** [comment]
@skjerns 
I could not reproduce the issue in my environment.
Please provide more information like:

- steps to reproduce the issue
- full source code
- your environment
- full error log

etc.

**Comment by skjerns** [comment]
Ah, seems to be my bad. I'm using iPython, and wrote following lines by hand:
```
from pytablewriter import TableWriterFactory
TableWriterFactory().create_from_file_extension('.csv')
```

as I don't assign it to a variable, it wants to print out the result to the console. This leads to an invocation of `__call__` and hence the error.

Strangely enough the code also did that when used in a script, but now I can't reproduce it either? Thanks anyway!
