### ISSUE TITLE
Get string output for markdown writer without printing to stdout

### ISSUE THREAD

**Issue by nettrino** [thombashi/pytablewriter#3]
Hello, 

I am trying to get the raw string output from a `MarkdownTableWriter` without printing 
to stdout. I have also tried redirecting output using the `with io.StringIO() as buf, redirect_stdout(buf):` pattern but that was unsuccessful. Trying to write to a file using
the example of the Readme leads to `AttributeError: 'MarkdownTableWriter' object has no attribute 'open'`. Any hints on how to resolve this? Essentially I just want a variable to hold all the contents of `writer.write_table()`

**Comment by nettrino** [comment]
Closing this as I resolved it using the [configure_stream.py example](https://github.com/thombashi/pytablewriter/blob/948ccdf2864988f1463f901c6024a5a3df09fdba/examples/py/stream/configure_stream.py). It would be useful if this was part of the README. It would be also an option that the default output is not stdout but that `write_table()` returns a string/iterator, that users can redirect as they wish.

**Comment by thombashi** [comment]
@nettrino 
Thank you for your feedback.

I had added dumps method at `pytablewriter 0.32.0` that can get `write_table()` output as an `str`, and added a description to the [README]( https://github.com/thombashi/pytablewriter#get-rendered-tabular-text-as-str ).
I would rather stay the default output of `write_table()`, for backward compatibility.
