### ISSUE TITLE
Set formatting for specific cell

### ISSUE THREAD

**Issue by Adamits** [thombashi/pytablewriter#33]
Hi,

Thanks for the awesome tool. I see that there is a `set_style` method for setting the style for a specific column by index. Is there a way to do this for a specific cell (e.g. indexed by the [x, y] row/col pair)? What i'd like to do is set the highest value of each column to be bolded (this is common when making tables for results of experiments) - so if there is any support for doing exactly that, which I have missed, being directed to it would be greatly appreciated :).

It would be cool to pass a function that tells the writer to iterate over columns and apply it, like:

```
writer.iter_col_styles(max, Style(font_weight="bold"))
```
or something like that...

Thanks!

**Comment by thombashi** [comment]
@Adamits 
Hi,

You can apply styles to specific cells by writing a style filter function and add it to a table writer instance via [add_style_filter](https://pytablewriter.readthedocs.io/en/latest/pages/reference/writers/base/abstract.html?highlight=add_style_filter#pytablewriter.AbstractTableWriter.add_style_filter) method.

An example of style filter function is as follows:
https://github.com/thombashi/pytablewriter-altrow-theme/blob/3531ecbc0936f7be7344f8bb7313c24ebf95da44/pytablewriter_altrow_theme/__init__.py#L42-L57
