### ISSUE TITLE
module 'dataproperty' has no attribute 'PropertyExtractor'

### ISSUE THREAD

**Issue by HoffErik-JohnerInst** [thombashi/pytablewriter#34]
While testing with your package and the excel module, I discovered an error, which I was not able to solve:

```
  File "C:\Users\Name\AppData\Roaming\Python\Python39\site-packages\pytablewriter\_excel_writer.py", line 176, in __init__
    super(ExcelTableWriter, self).__init__()
  File "C:\Users\Name\AppData\Roaming\Python\Python39\site-packages\pytablewriter\_table_writer.py", line 73, in __init__
    self._prop_extractor = dataproperty.PropertyExtractor()
AttributeError: module 'dataproperty' has no attribute 'PropertyExtractor'
```

Is there any way to solve this Issue?

Due to google results, I already tried an older Version (0.2.1), same issue here.

**Comment by thombashi** [comment]
@HoffErik-JohnerInst 
Please try to upgrade the package to the latest version.
Judging from the logs, it seems that the version you are using is too old.
