### ISSUE TITLE
Github Pages fail to render table

### ISSUE THREAD

**Issue by chchrist** [thombashi/pytablewriter#45]
Hello,

There is a bug with the jekyll markdown renderer that github pages are using where if there is no space between the table name and the table it can't render it... 
How should we approach this problem?
https://github.com/pages-themes/cayman/issues/82

**Comment by thombashi** [comment]
@chchrist 
Hello,

Please let me confirm.
Did you already tried a workaround that commented in the issue https://github.com/pages-themes/cayman/issues/82#issuecomment-613349240 ?
Does it not enough to solve your problem?

**Comment by chchrist** [comment]
This indeed fixes the problem but is a manual step and breaks the automation I put in place.
Unless maybe I can modify the payload before I save it?

**Comment by thombashi** [comment]
I mean the below description part:

```
You could change the setting in _config.yml from "kramdown" to "GFM" and see if this helps.
```

This will probably not break your automation.

**Comment by chchrist** [comment]
I've completely missed this step! Thank you that solves the issue!

**Comment by thombashi** [comment]
FYI: You can also set `kramdown`/`Jeklly` as a `flavor` for `MarkdownTableWriter` class since `pytablewriter 0.62.0`
