### ISSUE TITLE
Incorrect AsciiDoc table header generated.

### ISSUE THREAD

**Issue by jvdvegt** [thombashi/pytablewriter#47]
The AsciiDocTableWriter generates a table header which is not recognized by Asciidoc (but it is by asciidoctor-pdf):

An example of the table definition generated is:
[cols="<40,>5, <10, <31, <15, <59" options="header"]

Asciidoc 9.0.0rc1 does not like this:

line 29: illegal style name: cols="<40

This is fixed by separating the 'cols' and the 'options' with a comma, here: https://github.com/thombashi/pytablewriter/blob/29e8e7597d29c747354a64705313ad2e08013e4e/pytablewriter/writer/text/_asciidoc.py#L96

        rows = [f'[cols="{cols}", options="header"]']

This makes the resulting asciidoc look like this (note the comma before 'options') :
[cols="<40,>5, <10, <31, <15, <59", options="header"]

**Comment by thombashi** [comment]
Thank you for your report.

The problem fixed at `pytablewriter 0.63.0`
