### ISSUE TITLE
Show how to write to file in examples

### ISSUE THREAD

**Issue by fedderw** [thombashi/pytablewriter#56]
It's not obvious to all programmers (me) how to get the output from the writer object to, say, a markdown file.

**Comment by fedderw** [comment]
Oh ok, awesome, thanks! Can I write any string to the writer object?

**Comment by hugovk** [comment]
Yes, the first parameter to `writer.dump` can be whatever filename you like (or an output stream):

> **output** – The value must either an output stream or a path to an output file.

https://pytablewriter.readthedocs.io/en/latest/pages/reference/writers/text/markup/md.html?highlight=MarkdownTableWriter#pytablewriter.MarkdownTableWriter.dump

**Comment by thombashi** [comment]
@fedderw 
Thank you for your feedback, I had added a link to an example usage to the README:
https://github.com/thombashi/pytablewriter#write-a-markdown-table-to-a-stream-or-a-file

@hugovk 
Thank you for your answer.

**Comment by PabloPeso** [comment]
Is it possible to use `dump` to append the table to an existing file? I think at the moment it is overwriting by default. Thanks

**Comment by thombashi** [comment]
@PabloPeso 
This is possible with code like the following:

```py
from pytablewriter import MarkdownTableWriter


def main():
    writer = MarkdownTableWriter(
        table_name="example_table",
        headers=["int", "float", "str", "bool", "mix", "time"],
        value_matrix=[
            [0,   0.1,      "hoge", True,   0,      "2017-01-01 03:04:05+0900"],
            [2,   "-2.23",  "foo",  False,  None,   "2017-12-23 45:01:23+0900"],
            [3,   0,        "bar",  "true",  "inf", "2017-03-03 33:44:55+0900"],
            [-10, -9.9,     "",     "FALSE", "nan", "2017-01-01 00:00:00+0900"],
        ],
    )
    writer.write_table()
    with open("my_markdown.md", "a") as f:
        writer.dump(f)


if __name__ == "__main__":
    main()
```
