### ISSUE TITLE
[Bug] ModuleNotFoundError: No module named 'dominate'

### ISSUE THREAD

**Issue by johentsch** [thombashi/pytablewriter#58]
The following code is taken from my project where it has been working for a few years:

```python
import pytablewriter # v
df = pd.DataFrame.from_dict(
    {'my': {0: 9, 1: 8, 2: 8},
     'nice': {0: 51, 1: 56, 2: 58},
     'columns': {0: '2.3.0', 1: '2.3.0', 2: '2.3.0'}}
)
writer = pytablewriter.MarkdownTableWriter()
writer.table_name = "Metadata"
writer.header_list = list(df.columns.values)
writer.value_matrix = df.values.tolist()
print(str(writer))
```
<details>
<summary>Output</summary>

# Metadata
|my |nice|columns|
|--:|---:|-------|
|  9|  51|2.3.0  |
|  8|  56|2.3.0  |
|  8|  58|2.3.0  |

</details>

But strangely, when I import that same code as a function from a separate file I get the error mentioned in the title, but only in a Jupyter notebook.

**Steps to reproduce**

1. Create conda environment `conda create -y -n ptw python=3.10 && conda activate ptw`
1. `pip install pytablewriter pandas ipykernel`
    * same result with `pip install "pytablewriter<1.0.0" pandas==1.5.3 ipykernel`
1. Install ipykernel via `python -m ipykernel install --user --name=ptw`
1. Run a fresh Jupyter notebook, activate the `ptw` kernel
1. Create the file `external.py` next to the notebook containing
    ```python
    import pytablewriter
    
    def write_pytable(df):
        writer = pytablewriter.MarkdownTableWriter()
        writer.table_name = "Metadata"
        writer.header_list = list(df.columns.values)
        writer.value_matrix = df.values.tolist()
        return writer
    ```
1. In a notebook cell, execute
    ```python
    from external import write_pytable
    import pandas as pd
    
    df = pd.DataFrame.from_dict(
        {'my': {0: 9, 1: 8, 2: 8},
         'nice': {0: 51, 1: 56, 2: 58},
         'columns': {0: '2.3.0', 1: '2.3.0', 2: '2.3.0'}}
    )
    
    write_pytable(df)
    ```

<details>
<summary>Traceback</summary>

```python-traceback
~/miniconda3/envs/ptw/lib/python3.10/site-packages/pytablewriter/writer/text/_html.py:26: UserWarning: dependency packages for html not found.
you can install the dependencies with 'pip install pytablewriter[html]'

  warnings.warn(import_error_msg_template.format("html"))

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
File ~/miniconda3/envs/ptw/lib/python3.10/site-packages/IPython/core/formatters.py:344, in BaseFormatter.__call__(self, obj)
    342     method = get_real_method(obj, self.print_method)
    343     if method is not None:
--> 344         return method()
    345     return None
    346 else:

File ~/miniconda3/envs/ptw/lib/python3.10/site-packages/pytablewriter/writer/_table_writer.py:250, in AbstractTableWriter._repr_html_(self)
    240 writer = HtmlTableWriter(
    241     table_name=self.table_name,
    242     headers=self.headers,
   (...)
    246     enable_ansi_escape=self.enable_ansi_escape,
    247 )
    248 writer._dp_extractor = self._dp_extractor
--> 250 return writer.dumps()

File ~/miniconda3/envs/ptw/lib/python3.10/site-packages/pytablewriter/writer/text/_text_writer.py:313, in TextTableWriter.dumps(self, **kwargs)
    311 try:
    312     self.stream = io.StringIO()
--> 313     self.write_table(**kwargs)
    314     tabular_text = self.stream.getvalue()
    315 finally:

File ~/miniconda3/envs/ptw/lib/python3.10/site-packages/pytablewriter/writer/text/_html.py:77, in HtmlTableWriter.write_table(self, **kwargs)
     61 def write_table(self, **kwargs) -> None:
     62     """
     63     |write_table| with HTML table format.
     64 
   (...)
     74         - |None| values will be replaced with an empty value
     75     """
---> 77     tags, raw = _get_tags_module()
     78     write_css = kwargs.get("write_css", False)
     80     with self._logger:

File ~/miniconda3/envs/ptw/lib/python3.10/site-packages/pytablewriter/writer/text/_html.py:21, in _get_tags_module()
     19 def _get_tags_module() -> Tuple:
     20     try:
---> 21         from dominate import tags
     22         from dominate.util import raw
     24         return tags, raw

ModuleNotFoundError: No module named 'dominate'
```

</details>

Error occurs with both 0.64.2 and 1.0.0, but only in a notebook, not in a Python console. Also, it seems like it does not occur when installing `pytabledata[html]`.

**Update**: I could narrow it down a bit further, the error ocurs only when displaying the writer. So `markdown = write_pytable(df)` does not raise, but then having a cell containing only `markdown` does, meaning that it's caused by the `._repr_html_()` method that Jupyter tries for displaying. `.__repr__()` works perfectly.

**Comment by thombashi** [comment]
Thank you for your report.

This is expected behavior.
You can see the following warnings if the required dependency packages are not installed when you run notebook cells:

```
... UserWarning: dependency packages for html not found.
you can install the dependencies with 'pip install pytablewriter[html]'
```

However, this dependency is not clearly described in README or documentation.
I added some descriptions about this to be more precise.

**Comment by johentsch** [comment]
Conceptually, there is a difference between "I want to output tables as HTML" and "I want to display the library's object in a notebook". In my opinion it would be cleaner to simply handle the case within `._repr_html_()`, letting it fall back to `.__repr__()` if necessary.
