### ISSUE TITLE
New version ignores `header_list`

### ISSUE THREAD

**Issue by johentsch** [thombashi/pytablewriter#59]
Whereas this code used to work perfectly fine:

```python
import pytablewriter
import pandas as pd


df = pd.DataFrame.from_dict(
    {'my': {0: 9, 1: 8, 2: 8},
     'nice': {0: 51, 1: 56, 2: 58},
     'columns': {0: '2.3.0', 1: '2.3.0', 2: '2.3.0'}}
)

writer = pytablewriter.MarkdownTableWriter()
writer.header_list = list(df.columns.values) # <-- this line is without consequence.
writer.value_matrix = df.values.tolist()
```
producing as output

|my |nice|columns|
|--:|---:|-------|
|  9|  51|2.3.0  |
|  8|  56|2.3.0  |
|  8|  58|2.3.0  |

the new version `1.0.0` ignores the `header_list` and produces 

| A | B |  C  |
|--:|--:|-----|
|  9| 51|2.3.0|
|  8| 56|2.3.0|
|  8| 58|2.3.0|

instead. I will pin my library to `0.64.2` which was working perfectly fine but thought I'll let you know that such a change to the API breaks other peoples' workflows -- and unnecessarily AFAICT. That being said, thanks a lot for maintaining the package!

**Comment by thombashi** [comment]
Please use `headers` instead of `header_list`.

> **Note** You can set values from a pandas dataframe instance to a writer by  `from_dataframe` method more easily
>
> ```py
> writer = pytablewriter.MarkdownTableWriter()
> writer.from_dataframe(df)
> ```

`header_list` was removed at [pytablewriter v1](https://github.com/thombashi/pytablewriter/releases/tag/v1.0.0).
I deprecated `header_list` and added `DeprecationWarning` warns that `header_list` is deprecated and uses `headers` instead; I also rewrote all of the documentation and examples to use with `headers` (except a screenshot; I will replace that later).
These changes are made over the 3 years ago.
I assume that would be enough time for library users to move the new property usage.
Even though, as per your comment, deprecated methods deletion may break the backward compatibility.
So, I removed it at the time of the v1 release.

**Comment by thombashi** [comment]
I updated the screenshot

**Comment by johentsch** [comment]
Thanks for the quick reaction! As a maintainer you must be aware that it's impossible to follow up on the advancements of all the imported libraries. Personally, I see nothing wrong with leaving in an old property name as alias for a new one to increase backwards compatibility. But the `.from_dataframe()` is neat, thank you!

**Comment by thombashi** [comment]
I'm very confused.
You should have seen `DeprecationWarning` whenever you call `header_list` property.

**Comment by johentsch** [comment]
> You should have seen `DeprecationWarning` whenever you call `header_list` property.

Indeed, that would have been helpful.

> "maintainability" as I mentioned above, is a comment from the maintainer's perspective.

Would you mind elaborating on this? Not that I want to criticise how you name your properties ;-D I just fail to see the disadvantage for you as a maintainer of leaving in an alias: You just maintain `headers` and `header_list` simply passes onto that.

**Comment by thombashi** [comment]
Please do not ignore `DeprecationWarning`.
It just suggests simple replacements.
If you want to ignore `DeprecationWarning` and do not want to be affected by breaking changes of new releases, you can set the upper version limit constraint or pin the package versions with `pip`.
This package will follow Semver, so from now on; backward compatibility may break only when the major version upgrade.
And I always show warnings for a certain time before deleting deprecated methods/functions/properties.

> leaving in an alias: You just maintain headers and header_list

That will increase the maintenance cost of the library, which means reduced maintainability.
In addition, deprecated methods/functions/properties were not the only ones.
