### ISSUE TITLE
Handle colours

### ISSUE THREAD

**Issue by hugovk** [thombashi/pytablewriter#6]
It would be nice to be able to use the table with colours for output in a terminal. My use case is to report some data on a CI, and show good or bad values in green or red.

```python
import pytablewriter

from termcolor import colored

writer = pytablewriter.MarkdownTableWriter()
# writer = pytablewriter.SpaceAlignedTableWriter()

writer.header_list = ["int", "float", "str", "bool", "mix", "time"]
writer.value_matrix = [
    [colored(0, "red"), 0.1, "hoge", True, 0, "2017-01-01 03:04:05+0900"],
    [colored(2, "yellow"), "-2.23", "foo", False, None, "2017-12-23 45:01:23+0900"],
    [colored(3, "green"), 0, "bar", "true", "inf", "2017-03-03 33:44:55+0900"],
    [-10, -9.9, "", "FALSE", "nan", "2017-01-01 00:00:00+0900"],
]
writer.margin = 1  # add a whitespace for both sides of each cell

writer.write_table()
```

Produces this (colours not shown):
```
|    int     | float | str  | bool  |   mix    |           time           |
|------------|------:|------|-------|---------:|--------------------------|
| 0 |  0.10 | hoge | True  |        0 | 2017-01-01 03:04:05+0900 |
| 2 | -2.23 | foo  | False |          | 2017-12-23 45:01:23+0900 |
| 3 |  0.00 | bar  | True  | Infinity | 2017-03-03 33:44:55+0900 |
|        -10 | -9.90 |      | False |      NaN | 2017-01-01 00:00:00+0900 |
```

Terminal screenshot (macOS, iTerm):

![image](https://user-images.githubusercontent.com/1324225/46869610-0d81d080-ce35-11e8-8906-5ab163e9f21a.png)

It's accounting for the length of the string, which of course includes non-visible ANSI escape sequences.

Would it be possible or sensible to use the visible text when calculating the widths?

Here's one way: https://stackoverflow.com/a/2187024/724176.

**Comment by thombashi** [comment]
@hugovk 

Thank you for your feedback.
It looks like a good feature for text writers.

I had added ANSI color support at `pytablewriter 0.36.0`.
ANSI escape sequences will properly handle like follows:

    | int | float | str  | bool  |   mix    |           time           |
    |----:|------:|------|-------|---------:|--------------------------|
    |   0 |  0.10 | hoge | True  |        0 | 2017-01-01 03:04:05+0900 |
    |   2 | -2.23 | foo  | False |          | 2017-12-23 45:01:23+0900 |
    |   3 |  0.00 | bar  | True  | Infinity | 2017-03-03 33:44:55+0900 |
    | -10 | -9.90 |      | False |      NaN | 2017-01-01 00:00:00+0900 |

![image](https://user-images.githubusercontent.com/15517661/46905602-2ec7e700-cf31-11e8-95a3-36f36c2783a2.png)

**Comment by hugovk** [comment]
@thombashi Thank you for the fast implementation, it's working very nicely!
